# Generated by Django 5.2 on 2025-04-08 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('social_links', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(null=True, upload_to='')),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('genre', models.CharField(blank=True, choices=[('autobiographique', 'Autobiographique'), ('aventure', 'Aventure'), ('fantasy', 'Fantasy'), ('guerre', 'Guerre'), ('horreur', 'Horreur'), ('science-fiction', 'Science-Fiction'), ('western', 'Western'), ('documentaire', 'Documentaire'), ('erotique', 'Érotique'), ('fantastique', 'Fantastique'), ('historique', 'Historique'), ('humoristique', 'Humoristique'), ('muet', 'Muet'), ('pedagogique', 'Pédagogique'), ('policier', 'Polar-Policier'), ('roman-graphique', 'Roman-graphique'), ('comic-strip', 'Comic-strip'), ('shonen', 'Shonen'), ('seinen', 'Seinen'), ('shojo-josei', 'Shōjo/Josei'), ('auteurs', 'Auteurs'), ('webtoon', 'Webtoon')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('bd-adulte', 'BD Adulte'), ('bd-jeunesse', 'BD Jeunesse'), ('independants', 'Indépendants'), ('mangas', 'Mangas'), ('humour-bd', 'Humour BD'), ('comics', 'Comics')], max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_format', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('social_links', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicBookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('auteur', 'Auteur'), ('scénariste', 'Scénariste'), ('dessinateur', 'Dessinateur'), ('coloriste', 'Coloriste')], max_length=50)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.author')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.comicbook')),
            ],
            options={
                'unique_together': {('oeuvre', 'authors', 'role')},
            },
        ),
        migrations.AddField(
            model_name='comicbook',
            name='authors',
            field=models.ManyToManyField(through='bdtheque.ComicBookAuthor', to='bdtheque.author'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.comicbook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comicbook',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdtheque.publisher'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('summary', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.comicbook')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.comicbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdtheque.comicbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
