# Generated by Django 5.2 on 2025-11-06 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0002_authorfollow_publisherfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='comic_book',
            field=models.ManyToManyField(through='bdtheque.ComicBookAuthor', to='bdtheque.comicbook'),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('user', 'comic_book')},
        ),
        migrations.AlterUniqueTogether(
            name='usercollection',
            unique_together={('user', 'comic_book')},
        ),
        migrations.AlterUniqueTogether(
            name='userwishlist',
            unique_together={('user', 'comic_book')},
        ),
    ]
