# Generated by Django 5.2 on 2025-04-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0002_alter_usercollection_user_alter_userwishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicbookauthor',
            old_name='oeuvre',
            new_name='comic_book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='comic',
            new_name='comic_book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='work',
            new_name='comic_book',
        ),
        migrations.RenameField(
            model_name='usercollection',
            old_name='oeuvre',
            new_name='comic_book',
        ),
        migrations.RenameField(
            model_name='userwishlist',
            old_name='oeuvre',
            new_name='comic_book',
        ),
        migrations.AlterUniqueTogether(
            name='comicbookauthor',
            unique_together={('comic_book', 'authors', 'role')},
        ),
    ]
