# Generated by Django 5.2 on 2025-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0004_alter_author_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='comic_book',
            field=models.ManyToManyField(through='bdtheque.ComicBookAuthor', to='bdtheque.author'),
        ),
    ]
