# Generated by Django 5.2 on 2025-04-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0005_author_comic_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicbookauthor',
            old_name='authors',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='comicbookauthor',
            unique_together={('comic_book', 'author', 'role')},
        ),
    ]
