# Generated by Django 5.2 on 2025-04-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0006_rename_authors_comicbookauthor_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comic_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bdtheque.comicbook'),
        ),
    ]
