# Generated by Django 5.2 on 2025-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtheque', '0007_alter_review_comic_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='ean',
            field=models.CharField(default='', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
