# Generated by Django 5.2 on 2025-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('bdtheque', '0002_alter_usercollection_user_alter_userwishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.ManyToManyField(related_name='collection', through='bdtheque.UserCollection', to='bdtheque.comicbook'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', through='bdtheque.UserWishlist', to='bdtheque.comicbook'),
        ),
    ]
