# Generated by Django 5.2 on 2025-04-20 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('bdtheque', '0002_authorfollow_publisherfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authors_follow',
            field=models.ManyToManyField(related_name='authors_follow', through='bdtheque.AuthorFollow', to='bdtheque.author'),
        ),
        migrations.AddField(
            model_name='user',
            name='publisher_follow',
            field=models.ManyToManyField(related_name='publisher_follow', through='bdtheque.PublisherFollow', to='bdtheque.publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
